// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunSeqAnalysis(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RunSeqAnalysis'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function Write(arg1) {
  return window['go']['main']['App']['Write'](arg1);
}
