// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunSeqAnalysis(arg1:Array<string>):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function Write(arg1:Array<number>):Promise<number>;
