// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunSeqAnalysis(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:boolean,arg7:number):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function Write(arg1:Array<number>):Promise<number>;
